# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dev dependencies
        run: |
          pip install --upgrade pip
          pip install black flake8
      - name: Check formatting with Black
        run: black --check .
      - name: Run flake8 linter
        run: flake8 src tests

  test:
    name: Run Tests
    needs: lint-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with coverage
        run: pytest --cov=src --cov-report=xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  deploy:
    name: Deploy to Clever Cloud
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Install Clever Tools
        run: pip install clever-tools
      - name: Clever Cloud Login
        run: clever login --token "${{ secrets.CLEVER_TOKEN }}"
      - name: Deploy to Clever Cloud
        run: clever deploy --alias your-app-alias
