on:
  push:
    branches: ["refactor/clean-fsm-agents"]
  pull_request:
    branches: ["refactor/clean-fsm-agents"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: Python installieren
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        
