# .github/workflows/python-tests.yml
name: Python Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: Python installieren
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Tests ausführen
      env:
        OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
      run: |
        python -m unittest discover -s tests
